### ISSUE TITLE
Invalid types generates errors

### ISSUE THREAD

**Issue by jens-peterolsson** [cjoudrey/graphql-schema-linter#157]
E.g. if linting a schema with a type "string" instead of "String" in it. Should return a helpful validation error, not an unhandled js-error.

**Comment by cjoudrey** [comment]
Thanks for opening this issue @jens-peterolsson.

I believe this is issue is related to #53, #154, and #136.

The root cause is that the method this library (`buildASTSchema` from `graphql-js`) uses to parse / validate / build the GraphQL schema historically did not provide the right data to make the change you are suggesting. There is an open issue in `graphql-js` to address this: https://github.com/graphql/graphql-js/issues/546. I'll keep an eye on it.

**Comment by cjoudrey** [comment]
Will be fixed in next release by #163.
