### ISSUE TITLE
Rule naming convention 

### ISSUE THREAD

**Issue by goldcaddy77** [cjoudrey/graphql-schema-linter#17]
Currently rules are PascalCase. Would it make sense to switch to kebab-case to line up with other popular linters like [eslint](eslint.org/docs/rules/) and [tslint](https://palantir.github.io/tslint/rules/)?

**Comment by cjoudrey** [comment]
😆 that's the first time I hear kebab-case. I'll have to use that more often. haha 😀 

For the code, I used PascalCase because that's what `GraphQL.js` uses: https://github.com/graphql/graphql-js/blob/master/src/validation/rules/ScalarLeafs.js.

I'm guessing you're referring to the CLI options `--only` and `--except`, correct? I wouldn't mind adding support for `kebab-case` and updating the README.

**Comment by goldcaddy77** [comment]
👍 Yeah I was referring to the names of the rules: https://github.com/cjoudrey/graphql-schema-linter#built-in-rules
