### ISSUE TITLE
Running linter on template literals (gql`...`) instead of .graphql files

### ISSUE THREAD

**Issue by glambert** [cjoudrey/graphql-schema-linter#182]
Hi! 👋 

First, great library! I was wondering, what would be the effort required in order to have this run on `gql` template literals instead of `.graphql` files? We use Apollo Server and would look to run this linter on our schemas (we use `import { gql } from 'apollo-server-core';` to define them in `.js` files).

We would be happy to contribute if this is feasible.

Thanks!

**Comment by cjoudrey** [comment]
Hi Guillaume! 

I've never used `apollo-server-core`, but I'd happily welcome contributions that add support for it.

As a workaround, you can output a static `.graphql` file that you provide to `graphql-schema-linter`. While this will allow you to validate the schema, the error reporting won't be ideal as it will reference lines in the `.graphql` file instead of your `.js` files.

The tricky thing with supporting schemas defined in `.js` will be to parse and extract the definitions from the `.js` files. If we have those chunks of schema definitions and can preserve where they were originally defined then it should be no problem to have `graphql-schema-linter` output errors correctly.

A source of inspiration could be: https://github.com/apollographql/eslint-plugin-graphql

**Comment by glambert** [comment]
Thanks for the very quick reply!

In the end we'll probably look into https://github.com/prisma/graphql-import instead and rename our type definitions to `.graphql` which will also allow other languages to consume instead of only JavaScript/TypeScript.

**Comment by cjoudrey** [comment]
Going to close this issue because it's been inactive for quite some time. Feel free to comment/re-open if this is something you care about.

**Comment by glambert** [comment]
FYI what we did in the end was generate a static schema `.graphql` file from our Apollo Server's type definitions and run linting on this 👍
