### ISSUE TITLE
Remove `--except` and rename `--only` to `--rules`

### ISSUE THREAD

**Issue by goldcaddy77** [cjoudrey/graphql-schema-linter#25]
Most tools make you explicitly whitelist params.  This is nice because then you avoid the possibility of your project automatically picking up a new rule and starting to fail.  Also, technically each release that adds a new rule would likely be a "breaking change" requiring a major release.  Thoughts?

**Comment by cjoudrey** [comment]
To be honest, I based myself off a Ruby tool called [rubocop](https://github.com/bbatsov/rubocop) for the `--only` and `--except` options.

I'm with you on the fact that whitelists might be better in this situation since any new rule would automatically get adopted by users as they update the library.

Maybe we should remove `--except`. 🤔

**Comment by cjoudrey** [comment]
Just to recap our discussion from the PR #26, we said we would :fire: `--except` and rename `--only` to `--rules`.
