### ISSUE TITLE
New rule: spacing

### ISSUE THREAD

**Issue by cyberhck** [cjoudrey/graphql-schema-linter#286]
Hello there,
Thanks for this tool, it works great.

I was wondering if you have any plans on adding spacing rules like new lines before each type, new line before a description of a field, space between type name and a curly etc.

**Comment by cjoudrey** [comment]
Hi @cyberhck.  Thanks for the feedback. Glad you like the tool. ❤️ 

`graphql-schema-linter` doesn't really validate these kind of things because I felt like a tool like [`prettier`](https://prettier.io/) was better suited for this task. `graphql-schema-linter` is more interested by the parsed schema itself and not necessarily the details of how it was written in a file.

Hope that answers your question.

**Comment by cyberhck** [comment]
Thanks for the info :)
